version: '3'
services:
  gitlab:
   container_name: gitlab
   image: gitlab/gitlab-ce:latest
   restart: on-failure
   hostname: gitlab.test
   environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.test'
        # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - '8080:80'
     - '4433:443'
     - '222:22'
   volumes:
     - './config:/etc/gitlab'
     - './logs:/var/log/gitlab'
     - './data:/var/opt/gitlab'
   shm_size: '256m'