version: '3'
services:
  jenkins:
   container_name: jenkins
   image: jenkins/jenkins:lts
   ports:
      - "7070:8080"
      - "50000:50000"
   volumes:
     - ./home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
   restart: on-failure